# Generated by Django 5.2.5 on 2025-10-10 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='data_nascimento',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ong', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.TextField()),
                ('email_institucional', models.EmailField(max_length=254, unique=True)),
                ('nome_responsavel', models.CharField(max_length=200)),
                ('cpf_responsavel', models.CharField(max_length=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ong', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ONG',
                'verbose_name_plural': 'ONGs',
            },
        ),
        migrations.CreateModel(
            name='UsuarioComum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_comum', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário Comum',
                'verbose_name_plural': 'Usuários Comuns',
            },
        ),
    ]
