# Generated by Django 5.2.6 on 2025-10-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('porte', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=50)),
                ('peso', models.FloatField()),
                ('idade', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('obs', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotosPet/')),
                ('status', models.CharField(default='disponivel', max_length=100)),
                ('historico_saude', models.TextField()),
            ],
        ),
    ]
