# Generated by Django 5.2.6 on 2025-10-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='castrado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
