# Generated by Django 5.2.6 on 2025-10-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0002_pet_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotosPet/'),
        ),
    ]
