# Generated by Django 5.2.5 on 2025-10-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0002_pet_castrado'),
        ('ong', '0003_alter_pet_foto'),
    ]

    operations = [
    ]
