# Generated by Django 5.2.6 on 2025-10-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0004_merge_0002_pet_castrado_0003_alter_pet_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adotantes_padrinhos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='castrado',
            field=models.BooleanField(choices=[('True', 'Sim'), ('False', 'Não')]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('G', 'Gato'), ('C', 'Cachorro')], max_length=1),
        ),
    ]
