# Generated by Django 5.2.6 on 2025-10-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0005_pet_adotantes_padrinhos_alter_pet_castrado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='obs',
            new_name='info',
        ),
    ]
