# Generated by Django 5.2.6 on 2025-10-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0006_rename_obs_pet_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='historico_saude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
