# Generated by Django 5.2.6 on 2025-10-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0007_alter_pet_historico_saude_alter_pet_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='castrado',
            field=models.BooleanField(default=False),
        ),
    ]
