# Generated by Django 5.2.6 on 2025-10-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0008_alter_pet_castrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='castrado',
            field=models.BooleanField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default=False, max_length=3),
        ),
    ]
