# Generated by Django 5.2.6 on 2025-10-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0009_alter_pet_castrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='castrado',
            field=models.TextField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.TextField(choices=[('Gato', 'Gato'), ('Cachorro', 'Cachorro')], max_length=9),
        ),
    ]
