# Generated by Django 5.2.6 on 2025-10-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0010_alter_pet_castrado_alter_pet_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='castrado',
            field=models.TextField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3),
        ),
    ]
