# Generated by Django 5.2.6 on 2025-10-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0013_alter_pet_castrado_alter_pet_especie_alter_pet_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(default='Dísponivel', max_length=100),
        ),
    ]
