# Generated by Django 5.2.6 on 2025-10-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0014_alter_pet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(default='Disponível', max_length=100),
        ),
    ]
